### ISSUE TITLE
Organization support is buggy

### ISSUE THREAD

**Issue by rkh** [stillmaintained/stillmaintained#17]
I am owner of the sinatra organization and have explicit push access to sinatra/sinatra, yet only sinatra/sinatra.github.com shows up in my list.

**Comment by jeffkreeftmeijer** [comment]
That's not a bug in the organization support, this is because sinatra/sinatra is a fork and StillMaintained doesn't support forks right now. I'll dive in and see if I can think of a nice implementation. 

Here's the issue about forked projects: https://github.com/jeffkreeftmeijer/stillmaintained/issues#issue/13

**Comment by jeffkreeftmeijer** [comment]
You can add forked repositories now (they will get a status page but won't show up in the project lists), so #13 is closed. 

I created #18 since the implementation is still far from perfect.

**Comment by rkh** [comment]
still doesn't fit the sinatra case exactly, but fair enough. thanks for your hard work.
