### ISSUE TITLE
Cannot log in

### ISSUE THREAD

**Issue by ghedo** [stillmaintained/stillmaintained#23]
I've not been able to log in for some days. Every time I click on the login button, the _Woah, something went wrong_ page appears.

I've already tried to remove all the cookies (both GitHub and stillmaintained) and remove stillmaintained from the GitHub connections list, but after re-authorizing  stillmaintained via the GitHub app authorization page, the stillmaintained error page appears.

I may be doing something wrong though. Since I've never logged in to stillmaintained  before, apart from the initial setup, I can't say if it ever worked.

**Comment by jeffkreeftmeijer** [comment]
Hi Alex,

@CapnKernul messaged me about this on Twitter a while back too. I updated Mongoid, which switched to ObjectIDs instead of strings, like they did before. I didn't know StillMaintained was on such an old version, and the tests passed (since the test database clears every time the test run, there are no old records) after the update. I'm sorry for the inconvenience, I converted the database and everything should be working now.

Thanks for reporting!
- Jeff

**Comment by inkel** [comment]
That's strange. I revoke my permission to do the site and re-connect my account, and it worked.

Could you paste the URL of the _woah, something went wrong_ page?

**UPDATE**: so the issue updated when I was typing my response, hehe.

**Comment by ghedo** [comment]
On Thu, Jun 02, 2011 at 06:46:34AM -0700, jeffkreeftmeijer wrote:

> @CapnKernul messaged me about this on Twitter a while back too. I updated 
> Mongoid, which switched to ObjectIDs instead of strings, like they did 
> before. I didn't know StillMaintained was on such an old version, and the 
> tests passed (since the test database clears every time the test run, 
> there are no old records) after the update. I'm sorry for the 
> inconvenience, I converted the database and everything should be working 
> now.

Confirmed that it works now. Thank you very much.

**Comment by jeffkreeftmeijer** [comment]
@inkel that's because your account already existed before Mongoid got updated, so it still had a string ID. This bug only affected new users. :)
