### ISSUE TITLE
Taking over the project

### ISSUE THREAD

**Issue by jeffkreeftmeijer** [stillmaintained/stillmaintained#28]
Since I announced that StillMaintained would be closing down, I got some e-mails from people wanting to take over the project to lead it forward. After replying to some of you, I realised it'd probably be a better idea to have you team up and continue working on the project together, or to at least have a single place to talk about this instead of replying to all of you separately. 

I've sent everybody that contacted me a link to this issue and I hope you guys reply to this issue to get a new team going. :)

**Comment by jadb** [comment]
Hi Jeff, and everyone else,

I first contacted Jeff a couple months ago before getting very distracted with my wedding, honeymoon.... and my business of course. 

Jeff, i am still eager to take care of this project moving forward and will be glad to work with anyone else that is interested in maintaining it and/or helping to grow it.  

I had already set up a server for it that i had to shut down a couple weeks ago because it wasnt being used yet but ready to have it back up starting next week when i get back home. 

Cheers,

Jad

**Comment by BigBlueHat** [comment]
@jadb congrats on your wedding. :)

I'd love to see StillMaintained.com still be maintained, and am happy to help where I can. Jad, it sounds like you may already have the hosting stuff ready (or easily ready). If not, another option might be to contact EngineYard (which I can do, or we can ask other similar hosts) to see about sponsoring the app's hosting.

Anyway, I hate to see good ideas die, so Jad if you've not go the cycles, let me know. Otherwise, keep me posted on how I might help.

Thanks!

**Comment by jadb** [comment]
Hi guys,

I am back!

@BigBlueHat I don't mind sponsoring the app's hosting for the time being. Not sure what it takes to get sponsored by EngineYard or the likes, but I am confident that my company can handle the cost of hosting this project for the time being.

If you want to give a hand and because, as you can expect, I have a big backlog after a long holiday, I can have 2 machines back up as soon as you are ready for you to set them up and get the app running?

We can discuss further development of the app later this month if you want.

Let me know what you think and when I should have the servers started.

Cheers,

Jad

**Comment by doriath** [comment]
Hi guys,

What is the status of taking over the project? Is there any chance that it will be maintained again?

I will be glad to help in further development.

Cheers,
Tomek

**Comment by jadb** [comment]
Hey @doriath,

I was waiting on @BigBlueHat to reply but nothing thus far.

If you are interested in helping me getting the site setup, let me know.

As I previously stated, I had a server ready but then stopped it after saving an image of it because I got really busy and wanted to cut down on unnecessary costs. I have now restarted the server based on that old image and it should be all ready.

Did not get time to look at it yet but IIRC, I had installed a dummy SM based on the code and just needed to import the database.

If you are interested in helping, please let me know. Then we can get the latest database dump from @jeffkreeftmeijer and get it done.

Cheers,

Jad

**Comment by BigBlueHat** [comment]
Yeah, sorry guys. I've taken a new job last week and that's displaced the time I thought I'd have for this...I'm happy to promote this site once it's back up, but I realize that's marginal help...

Hope it goes well, and I'll try and check in once things settle down here.

Looks like we're all busy. Guess/hope that's good! ;)

**Comment by jeffkreeftmeijer** [comment]
Hey @doriath end @jadb,

You both e-mailed me directly, but I really want to keep the conversation open to make sure everybody knows who's working on what. That'll make sure you're not all working on the same thing.

I've sent Jad a database dump a while back and that's still current (the "add new projects"-button has been disabled since), and that's been imported on the StillMaintained version that's running on Jad's servers. (I'm not sharing the url because Jad hasn't yet, so I figure he's choosing not to)

That version might need some work, like removing the Webbynode logo and RubyRow ad, but we're about ready to move the domain name, so I'll go get an auth code and I'll contact Had directly about that.

Thanks for helping out, guys. :)

**Comment by jeffkreeftmeijer** [comment]
Hey @doriath and @jadb,

Sorry for not responding earlier. Here are some more questions to answers Jad asked me:

> I will initiate the domain transfer now and I think it can take a couple days for the transfer to happen. Maybe you could already start pointing the domain to my servers so it starts serving the right website after we make the remaining changes you mentioned in your post?

That's no problem at all. Please let me know when you've removed the Rubyrow and Webbynode links and I'll point the domain to your servers right away.

> Finally, what do you want to do with the repo? Do you want to add @doriath as collaborator or give me access to add collaborators or your prefer we move to a fork or move the repo's ownership?

We're in the new StillMaintained org right now, and you're an admin, so it'd be great if you could invite the rest of the team yourself. :)

Thanks again, guys. :)

**Comment by doriath** [comment]
Hej @jeffkreeftmeijer and @jadb,

Could you add me to the organization as collaborator? For now I will use pull requests to contribute to the project.

I sent two pull requests: one with removed the Rubyrow and Webbynode links and the other updating the repository location. After those changes are merged, I will deploy the new version.

The next thing I would like to do is to update the dependencies. I am using Mac OS X 10.7.4, with ruby 1.9.3-p194 and bundle was not able to install dependencies (chalofa_ruby-progressbar gem was not found and later RedCloth gem was not able to compile in version 4.2.7).

Let me know, if there is anything I can help with.

Cheers,
Tomasz

**Comment by jadb** [comment]
Thanks @jeffkreeftmeijer!

I created the collaborators team and added @doriath to it.

@doriath, go ahead, merge the pull requests you have made now that you can and confirm back here please for @jeffkreeftmeijer to point the domain to the server.

I have just finished setting up the named configuration.

Thanks guys!

**Comment by doriath** [comment]
Thanks @jadb for adding me as collaborator. I merged the pull requests and deployed new version. The links to the Rubyrow and Webbynode have been removed, and link to new github repository is used.

Thanks
Tomasz

**Comment by jeffkreeftmeijer** [comment]
Hey guys,

I set out to switch to Jad's name servers, but I can't change anything anymore since we're already transferring the domain name. I guess we'll just have to wait.

**Comment by doriath** [comment]
The domain stillmaintained.com is pointing on new server and stillmaintained is up and running again :).

**Comment by jadb** [comment]
I think we can close this issue now. If anyone believes it should be reopened, feel free to do so.
