### ISSUE TITLE
Travis CI have updated their status buttons

### ISSUE THREAD

**Issue by treffynnon** [stillmaintained/stillmaintained#36]
As you may already know Travis CI have updated their status buttons to make them easier to read. So for example:

![Travis CI status](https://secure.travis-ci.org/treffynnon/Navigator.png?branch=master)

So now the still maintained buttons look a little odd beside them. For an example please see: https://github.com/treffynnon/Navigator

More details about the status button change can be found in this tweet from the button creator: https://twitter.com/olivierlacan/status/305995717758046209

**Comment by ELLIOTTCABLE** [comment]
+1

**Comment by AlekSi** [comment]
:+1:

**Comment by Jamesking56** [comment]
:+1:

**Comment by ELLIOTTCABLE** [comment]
Update: @whit537 has taken over the project, and is providing a service to generate nice badges.

It should be trivial to update stillmaintained to use that generational service, now, so they look good alongside all the other useful badges.

(Also, it supports Retina displays, so that's a plus … no more fugly-ass 1x “still maintained” badge.)
